version: '3.8'

services:
  app:
    build: .
    image: ${TEST_IMAGE_TAG}
    ports:
      - "8000:8000"
    environment:
      TZ: Europe/Kyiv
      REDIS_URL: redis://db:6379
    depends_on:
      db:
        condition: service_healthy

  db:
    image: redis:7-alpine
    environment:
      TZ: Europe/Kyiv
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5